### ISSUE TITLE
Latest helm has older images, then previous.

### ISSUE THREAD

**Issue by yaroslav-nakonechnikov** [openbao/openbao-helm#25]
Hello, 

just noticed, that 0.5.1 using more fresh container of hashicorp/vault-csi-provider then 0.6.0:

https://github.com/openbao/openbao-helm/blob/openbao-0.6.0/charts/openbao/values.yaml#L1103
vs
https://github.com/openbao/openbao-helm/blob/openbao-0.5.1/charts/openbao/values.yaml#L1096

is it on purpose?

**Comment by JanMa** [comment]
Hey @yaroslav-nakonechnikov,

this is on purpose. We only got the CSI driver integration working with chart 0.6.0. For this we chose to use version 1.4.0 of the upstream CSI driver because it is the last version which was released using the MPL. Version 1.4.1 and following are released with the BUSL license which we don't want to ship.
